name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: docs
        
      - name: Build documentation
        run: npm run docs:build
        working-directory: docs
        
      - name: Check build output
        run: |
          echo "Checking if base URL is applied correctly..."
          ls -la docs/.vitepress/dist/
          find docs/.vitepress/dist -name "*.html" | head -1 | xargs cat | grep -E "(href|src).*sense-table" || echo "Base URL not found in HTML"
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          enable_jekyll: false
          cname: smoosense.ai
          destination_dir: sense-table 